# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_url',
            field=models.TextField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
