# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_route_route_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_url',
            field=models.CharField(max_length=512),
        ),
    ]
